### ISSUE TITLE
Code And Learn 2018

### ISSUE THREAD

**Issue by hiroppy** [nodejsjp/node-1#1]
## [lib]: Convert to Arrow Function

- [x] lib/_http_client.js
- [x] lib/_http_common.js
- [x] lib/_http_outgoing.js
- [x] lib/_stream_readable.js
- [x] lib/_tls_common.js
- [x] lib/fs.js
- [x] lib/internal/bootstrap_node.js
- [x] lib/internal/child_process.js
- [x] lib/internal/crypto/cipher.js
- [x] lib/internal/process.js
- [x] lib/internal/process/warning.js
- [x] lib/internal/repl.js:148
- [x] lib/internal/socket_list.js
- [x] lib/internal/streams/async_iterator.js
- [x] lib/internal/v8_prof_processor.js
- [x] lib/net.js
- [x] lib/punycode.js
- [x] lib/readline.js
- [x] lib/repl.js
- [x] lib/zlib.js

## [src]: deprecated V8 API migration ([ref](https://github.com/nodejs/node/pull/24125))

- [x] src/bootstrapper.cc
- [x] src/node_serdes.cc
- [x] src/node_util.cc
- [ ] src/string_decoder.cc
- [x] src/timer_wrap.cc
- [x] src/uv.cc

## [test]: assert.strictEqual ([ref](https://github.com/nodejs/node/pull/24431))

- [x] test/parallel/test-child-process-cwd.js
- [ ] test/parallel/test-buffer-alloc.js
- [x] test/parallel/test-crypto-fips.js
- [x] test/parallel/test-crypto-lazy-transform-writable.js
- [ ] test/parallel/test-event-emitter-remove-all-listeners.js
- [x] test/parallel/test-file-write-stream.js
- [x] test/parallel/test-fs-write-buffer.js
- [ ] test/parallel/test-fs-write-string-coerce.js
- [x] test/parallel/test-fs-write.js
- [ ] test/parallel/test-http-1.0.js
- [x] test/parallel/test-http-default-encoding.js
- [x] test/parallel/test-http-parser.js
- [x] test/parallel/test-http-pause.js
- [ ] test/parallel/test-http-request-end.js
- [ ] test/parallel/test-http-upgrade-agent.js
- [ ] test/parallel/test-http-upgrade-client.js
- [x] test/parallel/test-http.js
- [x] test/parallel/test-http2-binding.js
- [ ] test/parallel/test-http2-multiheaders-raw.js
- [x] test/parallel/test-readline.js
- [ ] test/parallel/test-repl-envvars.js
- [ ] test/parallel/test-repl-persistent-history.js
- [x] test/parallel/test-repl-underscore.js
- [ ] test/parallel/test-stream-readable-destroy.js
- [x] test/parallel/test-stream-writable-destroy.js
- [x] test/parallel/test-stream-writev.js
- [x] test/parallel/test-stream2-basic.js
- [x] test/parallel/test-util-deprecate.js
- [x] test/pummel/test-http-many-keep-alive-connections.js

## [docs]: replace anonymous function with arrow function ([ref](https://github.com/nodejs/node/pull/24528))

- [x] doc/api/async_hooks.md
- [x] doc/api/errors.md
- [x] doc/api/util.md
- [x] doc/api/v8.md
- [x] doc/guides/writing-and-running-benchmarks.md
- [x] doc/guides/writing-tests.md

## [docs]: typo

- [x] Typo "this this" doc/api/http2.md:973

## Others
Let’s rename all error arguments in documentation to **err**

**Comment by joyeecheung** [comment]
About the C++ tasks (`src` files)

## Introduction

Previously v8 only has C++ APIs to

1. Create a JS Array via `Array::New(size)`
2. Set the elements of a JS array via `Object::Set()`

So for example to create a JS array of length 2 with known elements
in the C++ land, you'd usually do:

```c++
Local<Array> arr = Array::New(isolate);
arr->Set(context, 0, some_value).FromJust();
arr->Set(context, 1, another_value).FromJust();
```

This is conceptually equivalent to JS code:

```js
const arr = [];
arr[0] = some_value;
arr[1] = another_value;
```

Now there is a new API added in v8 that allows you to convert a C
array of `Local<Value>` with known length into a `v8::Array` easily:

```C++
Local<Value> values[] = { some_value, another_value };
// arraysize is a convenience template defined in node_internals.h
Local<Array> arr = Array::New(isolate, values, arraysize(values));
```

This can also be used to convert the values in a contiguous container e.g.
a `std::vector`

```C++
std::vector<Local<Value>> values;
// ....some code pushes a bunch of Local<Value> into the vector
Local<Array> arr = Array::New(isolate, values.data(), values.size());
```

The task is:

1. Find patterns that uses the old APIs (for example, search for `Array::New` that
  only passes `isolate` and a `size`, or just `isolate` and the default size 0), and
  check if it can be converted to use the
  new API. That is:
    - The elements being added is already in a contiguous container like `std::vector`
    - ..or, they are in a C array
    - ..or, if they are just a few known values that can be initialized in a C array
    on the stack
2. And covert the code to use the new API. It should be faster because the pattern
   `array->Set()` essentially goes through a very generic `Object::Set` which is slow,
   whereas the new API just packs the elements in a backing store in one go. And
   the usage should be easier to read than the old pattern.

## Example

For more background, see https://github.com/nodejs/node/pull/24125

```diff
diff --git a/src/bootstrapper.cc b/src/bootstrapper.cc
index c40b855b99..93c1035617 100644
--- a/src/bootstrapper.cc
+++ b/src/bootstrapper.cc
@@ -50,11 +50,12 @@ void SetupNextTick(const FunctionCallbackInfo<Value>& args) {
           .ToLocalChecked();
   run_microtasks_fn->SetName(FIXED_ONE_BYTE_STRING(isolate, "runMicrotasks"));

-  Local<Array> ret = Array::New(isolate, 2);
-  ret->Set(context, 0, env->tick_info()->fields().GetJSArray()).FromJust();
-  ret->Set(context, 1, run_microtasks_fn).FromJust();
+  Local<Value> ret[] = {
+    env->tick_info()->fields().GetJSArray(),
+    run_microtasks_fn
+  };

-  args.GetReturnValue().Set(ret);
+  args.GetReturnValue().Set(Array::New(isolate, ret, arraysize(ret)));
 }

 void PromiseRejectCallback(PromiseRejectMessage message) {
```

**Comment by sotayamashita** [comment]
List of solved issues:

- `lib/_http_outgoing.js`
- `[test]: test/pummel/test-http-many-keep-alive-connections.js`
- `[test]: test/parallel/test-child-process-cwd.js`
- `doc/api/util.md`

**Comment by ikasumiwt** [comment]
`src/timer_wrap.cc` file is removed by  https://github.com/nodejs/node/pull/21777/files PR
